apiVersion: v1
kind: Secret
metadata:
  name: prefect-data
type: Opaque
stringData:
  API_KEY: ""
  API_URL: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-smar-key
type: Opaque
#stringData: json file
  #cred.json: "plain text token"
data:
  cred.json: "Enter base64 json token"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prefect-agent-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prefect-agent
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 250m
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 500Mi
  behavior:
    scaleDown:
      policies:
      - type: Percent
        value: 100
        periodSeconds: 120
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-agent
  namespace: default
  labels:
    app: prefect-agent
spec:
  selector:
    matchLabels:
      app: prefect-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: prefect-agent
    spec:
      containers:
      - name: agent
        image: prefecthq/prefect:2-python3.11
        command: ["prefect", "agent", "start", "-m", "narq", "--hide-welcome"]
        imagePullPolicy: "IfNotPresent"
        env:
          - name: PREFECT_API_URL
            valueFrom:
              secretKeyRef:
                name: prefect-data
                key: API_URL
          - name: PREFECT_API_KEY
            valueFrom:
              secretKeyRef:
                name: prefect-data
                key: API_KEY
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: prefect-agent
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/status"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-agent-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: prefect-agent
  apiGroup: rbac.authorization.k8s.io